---
title: "In-class Exercise 3"
format: html
---

## Loading the packages

```{r}
pacman:: p_load(sf, ggstatsplot, tmap, tidyverse, knitr, GWmodel)
```

## Preparing the data

### Importing Hunan shapefile

```{r}
hunan_sf <- st_read(dsn = "D:/XieHaoyang3537/ISSS626-GAA-XieHaoyang/Hands-on_Ex/Hands-on_ex04/data/geospatial",
                    layer = "Hunan")
```

```{r}
hunan2012 <- read_csv("D:/XieHaoyang3537/ISSS626-GAA-XieHaoyang/Hands-on_Ex/Hands-on_ex04/data/aspatial/Hunan_2012.csv")
```

### Joining Hunan and Hunan_2012

```{r}
hunan_sf <- left_join(hunan_sf, hunan2012) %>%
  select(1:3, 7, 15, 16, 31, 32)
```

```{r}
hunan_sp <- hunan_sf %>%
  as_Spatial()
```

### Cross-validation

```{r}
bw_CV <- bw.gwr(GDPPC ~ 1,
                data = hunan_sp,
                approach = "CV",
                adaptive = TRUE,
                kernel = "bisquare",
                longlat = T)
bw_CV
```

```{r}
bw_AIC <- bw.gwr(GDPPC ~ 1,
                 data = hunan_sp,
                 approach = "AIC",
                 adaptive = FALSE,
                 kernel = "bisquare",
                 longlat = T)
bw_AIC
```

### Computing adaptive bandwidth

```{r}
gwstat <- gwss(data = hunan_sp,
               vars = "GDPPC",
               bw = bw_AIC,
               kernel = "bisquare",
               adaptive = FALSE,
               longlat = T)
```

```{r}
gwstat_df <- as.data.frame(gwstat$SDF)
```

```{r}
hunan_gastat <- cbind(hunan_sf,gwstat_df)
```

```{r}
#| fig-height: 9
#| echo: false
tm_shape(hunan_gastat) +
  tm_fill("GDPPC_LM",
          n = 5,
          style = "quantile") +
  tm_borders(alpha = 0.5)
```

